.PHONY: clean All

All:
	@echo "----------Building project:[ Praktika - Debug ]----------"
	@cd "Praktika" && "$(MAKE)" -f  "Praktika.mk"
clean:
	@echo "----------Cleaning project:[ Praktika - Debug ]----------"
	@cd "Praktika" && "$(MAKE)" -f  "Praktika.mk" clean
